import React, { useEffect, useRef } from 'react';
import { View, Image, StyleSheet, Animated, Easing } from 'react-native';
import { WARRIOR_BASE, WARRIOR_GEAR } from '../warriorLayers';
import { colors } from '../theme';

// The living, dressable warrior.
//
// Rendering model: a base body per tier (stripped to shorts) with transparent,
// pixel-aligned gear overlays stacked on top — one per equipped slot. Overlays
// were generated by editing the exact base image per slot, so every piece fits
// the body at every tier.
//
// Idle life (all layers move together so gear never slides off the body):
//  - breath: slow chest rise (scaleY)
//  - stance: continuous bob + tiny sway, like he's staying loose between rounds
//  - surge: every few seconds the aura glow behind him flares and he tenses
// Newly equipped pieces still flash in with a quick pop.
//
// z-order: legs under core under chest under back under shoulders under arms.
const LAYER_ORDER = ['legs', 'core', 'chest', 'back', 'shoulders', 'arms'];

export default function WarriorFigure({ tier, equippedSlots = [], width = 180, height = 240, animate = true }) {
  const t = Math.min(5, Math.max(1, tier));
  const breath = useRef(new Animated.Value(0)).current;
  const stance = useRef(new Animated.Value(0)).current;
  const surge = useRef(new Animated.Value(0)).current;
  const pops = useRef({}).current; // slot -> Animated.Value
  const prevSlots = useRef(new Set());

  useEffect(() => {
    if (!animate) {
      breath.setValue(0);
      stance.setValue(0);
      surge.setValue(0);
      return undefined;
    }
    const loops = [
      Animated.loop(
        Animated.sequence([
          Animated.timing(breath, { toValue: 1, duration: 1900, easing: Easing.inOut(Easing.sin), useNativeDriver: true }),
          Animated.timing(breath, { toValue: 0, duration: 1900, easing: Easing.inOut(Easing.sin), useNativeDriver: true }),
        ])
      ),
      Animated.loop(
        Animated.sequence([
          Animated.timing(stance, { toValue: 1, duration: 2600, easing: Easing.inOut(Easing.sin), useNativeDriver: true }),
          Animated.timing(stance, { toValue: 0, duration: 2600, easing: Easing.inOut(Easing.sin), useNativeDriver: true }),
        ])
      ),
      Animated.loop(
        Animated.sequence([
          Animated.delay(3600),
          Animated.timing(surge, { toValue: 1, duration: 420, easing: Easing.out(Easing.quad), useNativeDriver: true }),
          Animated.timing(surge, { toValue: 0, duration: 900, easing: Easing.inOut(Easing.quad), useNativeDriver: true }),
        ])
      ),
    ];
    loops.forEach((l) => l.start());
    return () => loops.forEach((l) => l.stop());
  }, [breath, stance, surge, animate]);

  // Pop-in any slot that just became equipped.
  useEffect(() => {
    const now = new Set(equippedSlots);
    for (const slot of now) {
      if (!prevSlots.current.has(slot)) {
        if (!pops[slot]) pops[slot] = new Animated.Value(0);
        if (animate) {
          pops[slot].setValue(0);
          Animated.spring(pops[slot], { toValue: 1, friction: 4, tension: 140, useNativeDriver: true }).start();
        } else {
          pops[slot].setValue(1);
        }
      }
    }
    prevSlots.current = now;
  }, [equippedSlots.join(',')]);

  const scaleY = breath.interpolate({ inputRange: [0, 1], outputRange: [1, 1.014] });
  const bobY = stance.interpolate({ inputRange: [0, 1], outputRange: [0, -4] });
  const sway = stance.interpolate({ inputRange: [0, 1], outputRange: ['-0.6deg', '0.6deg'] });
  const tense = surge.interpolate({ inputRange: [0, 1], outputRange: [1, 1.02] });
  const glowOpacity = Animated.add(
    breath.interpolate({ inputRange: [0, 1], outputRange: [0.18, 0.3] }),
    surge.interpolate({ inputRange: [0, 1], outputRange: [0, 0.45] })
  );
  const glowScale = surge.interpolate({ inputRange: [0, 1], outputRange: [1, 1.12] });

  const base = WARRIOR_BASE[t];
  if (!base) return null;

  return (
    <View style={{ width, height }}>
      <Animated.View
        pointerEvents="none"
        style={[styles.glow, {
          width: width * 0.72, height: height * 0.6,
          left: width * 0.14, top: height * 0.24,
          borderRadius: width * 0.36,
          opacity: glowOpacity,
          transform: [{ scale: glowScale }],
        }]}
      />
      <Animated.View style={[{ width, height }, styles.stack, { transform: [{ translateY: bobY }, { rotate: sway }, { scaleY }, { scale: tense }] }]}>
        <Image source={base} style={styles.layer} resizeMode="contain" />
        {LAYER_ORDER.filter((s) => equippedSlots.includes(s)).map((slot) => {
          const src = WARRIOR_GEAR[t] && WARRIOR_GEAR[t][slot];
          if (!src) return null;
          const pop = pops[slot];
          const style = pop
            ? { opacity: pop, transform: [{ scale: pop.interpolate({ inputRange: [0, 1], outputRange: [1.12, 1] }) }] }
            : null;
          return (
            <Animated.View key={slot} style={[styles.layerWrap, style]}>
              <Image source={src} style={styles.layer} resizeMode="contain" />
            </Animated.View>
          );
        })}
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  stack: { position: 'relative' },
  layerWrap: { ...StyleSheet.absoluteFillObject },
  layer: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  glow: {
    position: 'absolute',
    backgroundColor: colors.accent,
    shadowColor: colors.accent,
    shadowOpacity: 1,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
});
