import React, { useEffect, useRef } from 'react';
import { View, Image, StyleSheet, Animated, Easing } from 'react-native';
import { WARRIOR_BASE, WARRIOR_GEAR } from '../warriorLayers';

// The living, dressable warrior.
//
// Rendering model: a base body per tier (stripped to shorts) with transparent,
// pixel-aligned gear overlays stacked on top — one per equipped slot. Overlays
// were generated by editing the exact base image per slot, so every piece fits
// the body at every tier. The whole stack breathes via a slow scale/translate
// loop (layers move together, so gear never slides off the body), and newly
// equipped pieces flash in with a quick pop.
//
// z-order: legs under core under chest under back(pauldrons) under arms.
const LAYER_ORDER = ['legs', 'core', 'chest', 'back', 'arms'];

export default function WarriorFigure({ tier, equippedSlots = [], width = 180, height = 240 }) {
  const t = Math.min(5, Math.max(1, tier));
  const breath = useRef(new Animated.Value(0)).current;
  const pops = useRef({}).current; // slot -> Animated.Value
  const prevSlots = useRef(new Set());

  useEffect(() => {
    const loop = Animated.loop(
      Animated.sequence([
        Animated.timing(breath, { toValue: 1, duration: 1900, easing: Easing.inOut(Easing.sin), useNativeDriver: true }),
        Animated.timing(breath, { toValue: 0, duration: 1900, easing: Easing.inOut(Easing.sin), useNativeDriver: true }),
      ])
    );
    loop.start();
    return () => loop.stop();
  }, [breath]);

  // Pop-in any slot that just became equipped.
  useEffect(() => {
    const now = new Set(equippedSlots);
    for (const slot of now) {
      if (!prevSlots.current.has(slot)) {
        if (!pops[slot]) pops[slot] = new Animated.Value(0);
        pops[slot].setValue(0);
        Animated.spring(pops[slot], { toValue: 1, friction: 4, tension: 140, useNativeDriver: true }).start();
      }
    }
    prevSlots.current = now;
  }, [equippedSlots.join(',')]);

  const scaleY = breath.interpolate({ inputRange: [0, 1], outputRange: [1, 1.012] });
  const translateY = breath.interpolate({ inputRange: [0, 1], outputRange: [0, -1.5] });

  const base = WARRIOR_BASE[t];
  if (!base) return null;

  return (
    <Animated.View style={[{ width, height }, styles.stack, { transform: [{ translateY }, { scaleY }] }]}>
      <Image source={base} style={styles.layer} resizeMode="contain" />
      {LAYER_ORDER.filter((s) => equippedSlots.includes(s)).map((slot) => {
        const src = WARRIOR_GEAR[t] && WARRIOR_GEAR[t][slot];
        if (!src) return null;
        const pop = pops[slot];
        const style = pop
          ? { opacity: pop, transform: [{ scale: pop.interpolate({ inputRange: [0, 1], outputRange: [1.12, 1] }) }] }
          : null;
        return (
          <Animated.View key={slot} style={[styles.layerWrap, style]}>
            <Image source={src} style={styles.layer} resizeMode="contain" />
          </Animated.View>
        );
      })}
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  stack: { position: 'relative' },
  layerWrap: { ...StyleSheet.absoluteFillObject },
  layer: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
});
